# Generated by Django 3.2.25 on 2025-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20250318_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
    ]
